---
include:
  - https://gitlab.wikimedia.org/repos/sre/wmf-debci/raw/main/builddebs.yml
stages:
  - test
test:
  stage: test
  image:
    name: docker-registry.wikimedia.org/releng/tox-buster:latest
    entrypoint: [""]
  script:
    - tox
