[tox]
envlist = py3

[testenv]
deps =
    coverage
    mypy
    pip>=20.1b1
    pytest
    pytest-cov
    pytest-mock
    ruff
    types-PyMySQL
    types-setuptools
commands =
    pytest --cov-report=term --cov-report=html:cover/ --cov=wmfdb --no-cov-on-fail wmfdb/tests/unit
    ruff check .
    mypy .
setenv =
    WMFDB_SECTION_MAP_TEST_DATA = y
